[workspace]
resolver = "2"
members = ["crates/core", "crates/ooxml", "crates/wasm", "crates/xtask"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/xinyuehtx/office-R"

[workspace.dependencies]
office-core = { path = "crates/core" }
office-ooxml = { path = "crates/ooxml" }
serde = { version = "1", features = ["derive"] }

[profile.release]
# WASM 产物优化:体积优先
opt-level = "z"
lto = true
codegen-units = 1
